import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "./globals.css";
import Login from "@/components/Login";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import { SessionProvider } from "@/components/SessionProvider";

const playpenSans = Playpen_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en" className={playpenSans.className}>
      <body>
        <SessionProvider session={session}>
          {!session ? <Login /> : <div className="">{children}</div>}
        </SessionProvider>
      </body>
    </html>
  );
}
