import type { Metadata } from "next";
import { Playpen_Sans } from "@next/font/google";
import "./globals.css";
import Login from "@/components/Login";
// import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";

const playpenSans = Playpen_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en" className={playpenSans.className}>
      <body>{!session ? <Login /> : <div className="">{children}</div>}</body>
    </html>
  );
}
